# Put patches for BetonQuest's config here. The syntax is documented in the docs/API/ConfigPatcher.md
2.0.0.1:
  - type: SET
    key: journal.custom_model_data
    value: -1
2.0.0.2:
  - type: SET
    key: hook.decentholograms
    value: true
    override: false
  - type: SET
    key: default_hologram
    value: DecentHolograms,HolographicDisplays
    override: false
